config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users do
    resources :entries, only: [:show]
  end 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  
  resources :entries
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 80 }
  validates :body, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  attr_accessor :current_password
  validates :password, presence: { if: :current_password }
  
  
  has_many :entries, dependent: :destroy
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_action :require_user_logged_in
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    @user.assign_attributes(account_params)
    if @user.save
      flash[:success] = 'ユーザ情報を更新しました。'
      redirect_to :account
    else 
      flash.now[:danger] = 'ユーザ情報の更新に失敗しました。'
      render "edit"
    end 
  end
  
  private 
  
  #Strong Parameter  
  def account_params
    params.require(:user).permit(:name, :email)
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # moduleをMix-in  取り込む logged_in?メソッドはこの一行が無いと使えない
  include SessionsHelper
  
  private 
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url # redirect_toメソッドのときにはprefix_path は使わないで、prefix_urlを使う決まり
    end 
  end 
  
  def counts(user)
    @count_entries = user.entries.count
  end 
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  
  # コントローラでのコールバックは特に、ActiveRecordコールバックという
  # before_actionコールバックの :require_user_logged_in によって、この EntriesController の全アクションはログインが必須になります。
  before_action :require_user_logged_in
  
  # before_actionコールバック　　:destroy, :edit, :updateアクションが実行される前に correct_user が実行されます。
  before_action :correct_user, only: [:destroy, :edit, :update]
  
  
  def show
    
    @entry = current_user.entries.find_by(id: params[:id])
    
    unless @entry
      # ネストされたリソースのブログ記事へ
      @user = User.find(params[:user_id])
      @entry = @user.entries.find(params[:id])
      
    end 
  end
  
  def create
    @entry = current_user.entries.build(entry_params)
    if @entry.save
      flash[:success] = 'ブログを投稿しました。'
      redirect_to root_url
    else 
      @entries = current_user.entries.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'ブログの投稿に失敗しました。'
      @user = current_user
      render 'toppages/index'
    end 
  end

 
  def edit
    return @entry
  end
  
  # before_actionコールバックで、 @entryには、値が入ってる
  def update
    @entry.assign_attributes(entry_params)
    if @entry.save
      flash[:success] = '記事を変更しました。'
      redirect_to @entry
    else 
      flash.now[:danger] = '記事を変更できませんでした。'
      render "edit"
    end
  end 

  # @entryには、correct_userコールバックで検索してきたオブジェクトが入っています。
  def destroy
    @entry.destroy
    flash[:success] ="ブログを削除しました。"
    redirect_back(fallback_location: root_path)
  end
  
  
  private
  
  def entry_params
    params.require(:entry).permit(:title, :body)
  end 
  
  def correct_user
    @entry = current_user.entries.find_by(id: params[:id])
    unless @entry
      redirect_to root_url
    end 
  end
  
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  
  before_action :require_user_logged_in
  
  def show
    redirect_to :account
  end
  
  
  # current_userがいきなり使えるのは、親クラスのApplicationController で、
  # include SessionsHelper を書いていて、モジュールを取り込んでいるから(Mix-in)
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    current_password = account_params[:current_password]
    
    if current_password.present?
      if @user.authenticate(current_password)
        @user.assign_attributes(account_params)
        if @user.save
          flash[:success] = 'パスワードを変更しました。'
          redirect_to :account
        else 
          render "edit"
        end 
      else 
        @user.errors.add(:current_password, :wrong)
        render "edit"
      end 
    else 
      @user.errors.add(:current_password, :empty)
      render "edit"
    end
  end
  
  private 
  
  #ストロングパラメータ :user で通った
  def account_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else 
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  
  private 
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else 
      # ログイン失敗
      return false
    end 
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  # topoagesController  でいきなり　logged_in? メソッド　current_userメソッドが使えるのは、
  # 親クラスで、include SessionsHelper を書いて、モジュールを取り込んでるから(Mix-in)
  
  def index
    if logged_in?
      @entry = current_user.entries.build # form_with用 空のインスタンスを用意する
      @entries = current_user.entries.order(id: :desc).page(params[:page]) # 一覧表示用
      @user = current_user
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :destroy]
  
  
  def index
    @users = User.order(id: :asc).page(params[:page]).per(10)
  end

  # countsメソッドはすべてのコントローラで使えるように、ApplicationControllerにprivateなメソッドとして定義してある
  def show
    @user = User.find(params[:id])
    @entries = @user.entries.order(id: :desc).page(params[:page]).per(5)
    
    counts(@user)  # return省略してる
  end


  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else 
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end 
  end


  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      flash[:success] = 'ユーザのプロフィールを更新しました。'
      redirect_to @user
    else 
      flash.now[:danger] = 'ユーザのプロフィールの更新に失敗しました。'
      render "edit"
    end 
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザは正常に削除されました。'
    redirect_to users_url
  end
  
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def page_title
    title = "Blog"
    title = @page_title + " - " + title if @page_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end 
  
  def logged_in?
    !!current_user
  end 
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
  
end

app/views/accounts/edit.html.erb
<% @page_title = "アカウント情報の編集" %>

<h1><%= @page_title %></h1>

<div class="toolbar"><%= link_to "マイアカウントに戻る", :account %></div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, as: :account, url: :account, local: true) do |f| %>
      
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Update', class: 'btn btn-primary btn-block' %>
      
    <% end %>
    
  </div>
</div>

app/views/accounts/show.html.erb
<% @page_title = "マイアカウント" %>

<h1><%= @page_title %></h1>

<ul class="toolbar">
  <%= link_to "アカウント情報の編集", :edit_account %> | 
  <%= link_to "パスワードの変更", :edit_password %>
</ul>


<table class="table table-striped">
  
  <tr>
    <th>Profile Image</th>
   
    <td class="media"><img class="mr-2 rounded" src="<%= gravatar_url(@user, { size: 50 }) %>" alt=""></td>
    
  </tr>
  
  
  <tr>
    <th width="150">id</th>
    <td><%= @user.id %></td>
  </tr>

  <tr>
    <th>Name</th>
    <td><%= @user.name %></td>
  </tr>

  <tr>
    <th>Mail Address</th>
    <td><%= @user.email %></td>
  </tr>

</table>

app/views/entries/_entries.html.erb
<ul class="list-unstyled">
  <% entries.each do |entry| %>
    <li class="media mb-3">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to entry.user.name, user_path(entry.user) %> <span class="text-muted">posted at <%= entry.created_at %></span>
        </div>
        <div>
          <p><%= entry.title %></p>
        </div>
        <div>
          <p><%= truncate(entry.body, length: 80) %>
          
            <%= link_to "もっと読む", user_entry_path(entry.user, entry) %></p>
         
        </div>
        <% if current_user == entry.user %>
          <%= link_to "編集", edit_entry_path(entry), class: 'btn btn-success btn-sm' %>
        <% end %>
         
        <% if current_user == entry.user %>
          <%= link_to "削除", entry, method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger btn-sm' %>
        <% end %>
      </div>
    </li>
  <% end %>
  <%= paginate entries %>
  
</ul>

app/views/entries/edit.html.erb
<% @page_title = "ブログの編集" %>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @entry, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control', rows: 1 %>
      </div>
      
      <div class="form-group">
        <%= f.label :body, '本文' %>
        <%= f.text_area :body, class: 'form-control',  rows: 15 %>
        
        <%= f.submit 'Update', class: 'btn btn-primary btn-block' %>
      </div>
    
    <% end %>
    
  </div>
</div>

app/views/entries/show.html.erb
<% @page_title = @entry.title + " - " + @entry.user.name + "さんのブログ" %>
<h1><%= @entry.user.name %>さんのブログ</h1>

<div class="toolbar"><%= link_to "トップページへに戻る", "/" %></div>

<h2><%= simple_format(@entry.title) %></h2>
<div>
  <%= simple_format(@entry.body) %>
  
</div>


<div class="toolbar"><%= link_to @entry.user.name + "さんのぺーじへ戻る" , user_path(@entry.user) %></div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>


<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My Blog', user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'My Account', :account %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
          
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% @page_title = "toppage" %>
<% if logged_in? %>
  
  <div class="row">
    
    <aside class="col-sm-5">
      <%= form_with(model: @entry, local: true) do |f| %>
      
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
          <%= f.text_area :title, class: 'form-control', rows: 1, placeholder: "(例) タイトル" %>
        </div>
        <div>
          <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "(例) 本文" %>
        </div>
 
          <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>

      <% end %>
    </aside>
    
    <div class="col-sm-7">
      <%= render 'entries/entries', entries: @entries, user: @user %>
    </div>
  </div>
  
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Blog</h1>
      
      <%= link_to 'Sing up now!', signup_path, class: 'btn btn-lg btn-primary' %>
      
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      
      <% if @user.new_record? %>
        <div class="form-group">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :password_confirmation, 'Confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      <% end %>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
      
    <% end %>
    
  </div>
</div>

app/views/users/_users.html.erb
<% if users.any? %>

<div class="row">
  <div class="col-sm-8 offset-sm-2">

  <table class="table">
    <thead>
      <tr>
        <th class="text-center">プロフィール画像</th>
        <th class="text-center">id</th>
        <th class="text-center">氏名</th>
        <!--<th class="text-center">操作</th>-->
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td class="media"><img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt=""></td>
          <td><%= user.id %></td>
          <td><%= link_to user.name, user_path(user) %></td>
          <!--<td><　　%= link_to "編集", [:edit, user] %> | <　　%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate users %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<% @page_title = "Profile update" %>

<div class="text-center">
  <h1><%= @page_title %></h1>
</div>

<%= render "form" %>

app/views/users/index.html.erb
<% @page_title = "会員名簿" %>
<h1><%= @page_title %></h1>


<!--<div class="toolbar"><　　%= link_to "会員の新規登録", :new_user %></div>-->

<%= render 'users', users: @users %>

app/views/users/new.html.erb
<% @page_title = "Sign up" %>

<div class="text-center">
  <h1><%= @page_title %></h1>
</div>

<%= render "form" %>

app/views/users/show.html.erb
<% @page_title = "会員詳細" %>

<% if current_user == @user %>
  <div class="toolbar"><%= link_to "新規ブログを追加する", :root %></div>
<% end %>
<div class="row">
  
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 50 }) %>" alt="">
      </div>
    </div>
  </aside>
  
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item">
        <a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">
          Blog <span class="badge badge-secondary"><%= @count_entries %></span>
        </a>
      </li>
      
    </ul>
    <%= render 'entries/entries', entries: @entries %>
  </div>
  
</div>